const state = { checkedIn: true, onBreak: false, leaves: [
  { id: 1, name: 'Nadia Patel', initials: 'NP', color: 'lavender', type: 'Paid leave', dates: 'Aug 26 - Aug 28', status: 'Pending', note: 'Family event' },
  { id: 2, name: 'Rohan Shah', initials: 'RS', color: 'orange', type: 'Sick leave', dates: 'Aug 22', status: 'Pending', note: 'Medical appointment' },
  { id: 3, name: 'Ari Mehta', initials: 'AM', color: 'teal', type: 'Paid leave', dates: 'Aug 11 - Aug 12', status: 'Approved', note: 'Personal time' },
  { id: 4, name: 'Jamie Diaz', initials: 'JD', color: 'orange', type: 'Sick leave', dates: 'Aug 22', status: 'Approved', note: 'Rest and recovery' }
]};
const team = [
  ['Ari Mehta','HR Manager','AM','teal','Working today'], ['Sam Kim','Product Designer','SK','teal','On annual leave'], ['Jamie Diaz','Software Engineer','JD','orange','On sick leave'], ['Lin Nguyen','Data Analyst','LN','lavender','Working remotely'], ['Nadia Patel','Marketing Lead','NP','lavender','Working today'], ['Rohan Shah','Frontend Engineer','RS','orange','Working today']
];
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2800); }
function avatar(initials,color='teal'){ return `<span class="avatar ${color}">${initials}</span>`; }
function pending(){ return state.leaves.filter(l=>l.status==='Pending'); }
function renderApprovals(){ const el=$('#approvalList'), items=pending(); $('#pendingCount').innerHTML=`${items.length} <small>requests</small>`; $('#leaveBadge').textContent=items.length; el.innerHTML=items.length?items.map(l=>`<div class="request"><span>${avatar(l.initials,l.color)}</span><p>${l.name}<small>${l.type} · ${l.dates}</small></p><div class="request-actions"><button class="approve" data-action="approve" data-id="${l.id}">Approve</button><button class="reject" data-action="reject" data-id="${l.id}">Decline</button></div></div>`).join(''):'<p class="muted">All caught up - there are no requests awaiting review.</p>'; }
function renderLeaves(){ const choice=$('#leaveFilter').value; const rows=state.leaves.filter(l=>choice==='all'||l.status===choice); $('#leaveTable').innerHTML=rows.map(l=>`<tr><td><span class="person">${avatar(l.initials,l.color)} ${l.name}</span></td><td>${l.type}</td><td>${l.dates}</td><td><span class="status ${l.status}">${l.status}</span></td><td class="row-actions">${l.status==='Pending'?`<button class="approve" data-action="approve" data-id="${l.id}">Approve</button><button class="reject" data-action="reject" data-id="${l.id}">Reject</button>`:'<button class="text-button" data-action="details" data-id="${l.id}">Details</button>'}</td></tr>`).join(''); }
function act(e){ const btn=e.target.closest('[data-action]'); if(!btn)return; const item=state.leaves.find(l=>l.id===+btn.dataset.id); if(btn.dataset.action==='details')return toast(`${item.name}: ${item.note}`); item.status=btn.dataset.action==='approve'?'Approved':'Rejected'; renderApprovals(); renderLeaves(); toast(`${item.name}'s request was ${item.status.toLowerCase()}.`); }
function renderCalendar(){ const grid=$('#calendarGrid'); const days=Array.from({length:20},(_,i)=>i+3); grid.innerHTML=days.map(d=>{let c=''; let label=''; if([3,4,5,6,7,10,13,14,17,18,19,20,21].includes(d)){c='present';label='Present'}if([11,12].includes(d)){c='leave';label='Leave'}if(d===15){c='remote';label='Remote'}if(d===22){c='present';label='Today'}return `<div class="day ${c}">${d}${label?`<b>${label}</b>`:''}</div>`}).join(''); }
function renderTeam(query=''){ const q=query.toLowerCase(); $('#teamGrid').innerHTML=team.filter(x=>x[0].toLowerCase().includes(q)||x[1].toLowerCase().includes(q)).map(x=>`<article class="team-member"><header>${avatar(x[2],x[3])}<div><h3>${x[0]}</h3><p>${x[1]}</p></div></header><footer>${x[4]}</footer></article>`).join(''); }
function switchView(view){ $$('.view').forEach(v=>v.classList.toggle('active',v.id===view)); $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); const title={dashboard:'Good morning, Ari',attendance:'Attendance',leave:'Time off',team:'Team directory',payroll:'Payroll',profile:'My profile'}; $('#pageTitle').textContent=title[view]; window.scrollTo({top:0,behavior:'smooth'}); }
function setAttendance(){ const btn=$('#checkInButton'), secondary=$('#attendanceAction'); btn.innerHTML=state.checkedIn?'Checked in <span>✓</span>':'Check in <span>→</span>'; secondary.textContent=state.checkedIn?'Checked in ✓':'Check in'; $('.live-dot').textContent=state.checkedIn?(state.onBreak?'● On break':'● Working'):'● Not checked in'; }
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view))); $$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.viewTarget)));
document.addEventListener('click',act); $('#leaveFilter').addEventListener('change',renderLeaves); $('#teamSearch').addEventListener('input',e=>renderTeam(e.target.value));
function toggleCheck(){state.checkedIn=!state.checkedIn;state.onBreak=false;setAttendance();toast(state.checkedIn?'You are checked in. Have a focused day!':'You are checked out. See you next time.');} $('#checkInButton').addEventListener('click',toggleCheck); $('#attendanceAction').addEventListener('click',toggleCheck); $('#checkOutButton').addEventListener('click',()=>{if(!state.checkedIn)return toast('You are already checked out.');toggleCheck()});
$('#breakButton').addEventListener('click',e=>{if(!state.checkedIn)return toast('Check in before starting a break.');state.onBreak=!state.onBreak;e.target.textContent=state.onBreak?'End break':'Start break';setAttendance();toast(state.onBreak?'Your break has started.':'Welcome back!');});
$('#newLeaveButton').addEventListener('click',()=>$('#leaveModal').classList.add('open')); $('#closeModal').addEventListener('click',()=>$('#leaveModal').classList.remove('open')); $('#leaveModal').addEventListener('click',e=>{if(e.target.id==='leaveModal')e.currentTarget.classList.remove('open')});
$('#leaveForm').addEventListener('submit',e=>{e.preventDefault();const start=$('#leaveStart').value,end=$('#leaveEnd').value;if(!start||!end)return;const format=d=>new Date(`${d}T00:00:00`).toLocaleDateString('en-IN',{month:'short',day:'numeric'});state.leaves.unshift({id:Date.now(),name:'Ari Mehta',initials:'AM',color:'teal',type:$('#leaveType').value,dates:`${format(start)} - ${format(end)}`,status:'Pending',note:$('#leaveNotes').value||'No note supplied'});$('#leaveModal').classList.remove('open');e.target.reset();renderApprovals();renderLeaves();toast('Your leave request was submitted.');});
$('#saveProfile').addEventListener('click',()=>toast('Your profile changes have been saved.')); $('#addEmployee').addEventListener('click',()=>toast('Invite flow coming soon.')); $('#roleSwitch').addEventListener('click',()=>toast('You are viewing the HR Manager workspace.'));
$('#welcomeDate').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); renderApprovals();renderLeaves();renderCalendar();renderTeam();setAttendance();
